const INTERACTION_TYPES = [
  "Assigned Task",
  "Self-Assigned Task",
  "Unassigned Task",
  "Started Task",
  "Restarted Task",
  "Completed Task",
  "Incomplete Task",
  "Inactive Task",
  "Deleted Task",
  "Changed Task Assignee",
  "Changed Task Instructions",
  "Changed Task Start Date",
  "Changed Task End Date",
  "Deleted Recurring Task",
  "Changed Recurring Task Name",
  "Changed Recurring Task Days",
  "Changed Recurring Task Cadence",
  "Changed User Name",
  "Changed User Color Level",
  "Changed User Role",
  "Invited User",
  "Deleted User",
  "Deleted Pet",
  "Changed Pet Name",
  "Changed Pet Color Level",
  "Changed Pet Neuter Status",
  "Changed Pet Safety Info",
  "Changed Pet Medical Info",
  "Changed Pet Management Info",
  "Deleted Task Template",
  "Changed Task Template Name",
  "Changed Task Template Instructions",
];

export default INTERACTION_TYPES;
