import { QueryInterface } from "sequelize";
import { Role, UserStatus, AnimalTag, PetStatus, TaskCategory, Sex } from "../types";

export default {
  up: async (queryInterface: QueryInterface) => {
    await queryInterface.bulkInsert("Users", [
      // Administrators
      {
        first_name: "John",
        last_name: "Smith",
        auth_id: "admin_001",
        role: Role.ADMINISTRATOR,
        email: "john.smith@humanesociety.com",
        color_level: 5,
        animal_tags: "Dog,Cat",
        status: UserStatus.ACTIVE,
        can_see_all_logs: true,
        can_assign_users_to_tasks: true,
        phone_number: "+1-555-0101",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        first_name: "Sarah",
        last_name: "Johnson",
        auth_id: "admin_002",
        role: Role.ADMINISTRATOR,
        email: "sarah.johnson@humanesociety.com",
        color_level: 5,
        animal_tags: "Bird,Small Animal",
        status: UserStatus.ACTIVE,
        can_see_all_logs: true,
        can_assign_users_to_tasks: true,
        phone_number: "+1-555-0102",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        first_name: "Dr. Emily",
        last_name: "Wilson",
        auth_id: "behaviourist_001",
        role: Role.ANIMAL_BEHAVIOURIST,
        email: "emily.wilson@humanesociety.com",
        color_level: 5,
        animal_tags: "Dog,Cat,Small Animal",
        status: UserStatus.ACTIVE,
        can_see_all_logs: true,
        can_assign_users_to_tasks: false,
        phone_number: "+1-555-0201",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        first_name: "Dr. Michael",
        last_name: "Brown",
        auth_id: "behaviourist_002",
        role: Role.ANIMAL_BEHAVIOURIST,
        email: "michael.brown@humanesociety.com",
        color_level: 4,
        animal_tags: "Bird,Bunny",
        status: UserStatus.ACTIVE,
        can_see_all_logs: true,
        can_assign_users_to_tasks: false,
        phone_number: "+1-555-0202",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // Staff Members
      {
        first_name: "Lisa",
        last_name: "Davis",
        auth_id: "staff_001",
        role: Role.STAFF,
        email: "lisa.davis@humanesociety.com",
        color_level: 4,
        animal_tags: "Dog,Cat",
        status: UserStatus.ACTIVE,
        can_see_all_logs: false,
        can_assign_users_to_tasks: true,
        phone_number: "+1-555-0301",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        first_name: "Robert",
        last_name: "Miller",
        auth_id: "staff_002",
        role: Role.STAFF,
        email: "robert.miller@humanesociety.com",
        color_level: 3,
        animal_tags: "Bunny,Small Animal",
        status: UserStatus.ACTIVE,
        can_see_all_logs: false,
        can_assign_users_to_tasks: true,
        phone_number: "+1-555-0302",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // Volunteers
      {
        first_name: "Amanda",
        last_name: "Garcia",
        auth_id: "volunteer_001",
        role: Role.VOLUNTEER,
        email: "amanda.garcia@volunteer.com",
        color_level: 2,
        animal_tags: "Dog",
        status: UserStatus.ACTIVE,
        can_see_all_logs: false,
        can_assign_users_to_tasks: false,
        phone_number: "+1-555-0401",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        first_name: "Kevin",
        last_name: "Martinez",
        auth_id: "volunteer_002",
        role: Role.VOLUNTEER,
        email: "kevin.martinez@volunteer.com",
        color_level: 1,
        animal_tags: "Cat,Bird",
        status: UserStatus.ACTIVE,
        can_see_all_logs: false,
        can_assign_users_to_tasks: false,
        phone_number: "+1-555-0402",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);

    // Seed Pets - 5 of each animal type
    await queryInterface.bulkInsert("Pets", [
      // Dogs
      {
        animal_tag: AnimalTag.DOG,
        name: "Buddy",
        status: "Needs Care",
        breed: "Golden Retriever",
        birthday: "2022-03-15",
        weight: 65,
        color_level: 2,
        neutered: true,
        sex: "M",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        animal_tag: AnimalTag.DOG,
        name: "Luna",
        status: "Does Not Need Care",
        breed: "Labrador Mix",
        birthday: "2021-07-22",
        weight: 55,
        color_level: 3,
        neutered: true,
        sex: "F",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        animal_tag: AnimalTag.DOG,
        name: "Max",
        status: "Occupied",
        breed: "German Shepherd",
        birthday: "2020-11-08",
        weight: 75,
        color_level: 4,
        neutered: true,
        sex: "M",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        animal_tag: AnimalTag.DOG,
        name: "Bella",
        status: "Needs Care",
        breed: "Border Collie",
        birthday: "2023-01-30",
        weight: 45,
        color_level: 1,
        neutered: false,
        sex: "F",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        animal_tag: AnimalTag.DOG,
        name: "Charlie",
        status: "Does Not Need Care",
        breed: "Beagle",
        birthday: "2022-09-12",
        weight: 25,
        color_level: 2,
        neutered: true,
        sex: "M",
        created_at: new Date(),
        updated_at: new Date(),
      },
      // Cats
      {
        animal_tag: AnimalTag.CAT,
        name: "Whiskers",
        status: "Needs Care",
        breed: "Domestic Shorthair",
        birthday: "2022-05-20",
        weight: 10,
        color_level: 1,
        neutered: true,
        sex: "M",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        animal_tag: AnimalTag.CAT,
        name: "Mittens",
        status: "Does Not Need Care",
        breed: "Persian",
        birthday: "2021-12-03",
        weight: 12,
        color_level: 2,
        neutered: true,
        sex: "F",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        animal_tag: AnimalTag.CAT,
        name: "Shadow",
        status: "Occupied",
        breed: "Maine Coon",
        birthday: "2020-08-15",
        weight: 18,
        color_level: 3,
        neutered: true,
        sex: "M",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        animal_tag: AnimalTag.CAT,
        name: "Princess",
        status: "Needs Care",
        breed: "Siamese",
        birthday: "2023-02-28",
        weight: 8,
        color_level: 1,
        neutered: false,
        sex: "F",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        animal_tag: AnimalTag.CAT,
        name: "Tiger",
        status: "Does Not Need Care",
        breed: "Tabby",
        birthday: "2022-06-10",
        weight: 11,
        color_level: 2,
        neutered: true,
        sex: "M",
        created_at: new Date(),
        updated_at: new Date(),
      },
      // Birds
      {
        animal_tag: AnimalTag.BIRD,
        name: "Polly",
        status: "Needs Care",
        breed: "African Grey Parrot",
        birthday: "2019-04-12",
        weight: 1.5,
        color_level: 4,
        sex: "F",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        animal_tag: AnimalTag.BIRD,
        name: "Rio",
        status: "Does Not Need Care",
        breed: "Cockatiel",
        birthday: "2021-10-05",
        weight: 0.3,
        color_level: 2,
        sex: "M",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        animal_tag: AnimalTag.BIRD,
        name: "Sunny",
        status: "Occupied",
        breed: "Canary",
        birthday: "2022-01-18",
        weight: 0.2,
        color_level: 1,
        sex: "F",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        animal_tag: AnimalTag.BIRD,
        name: "Kiwi",
        status: "Needs Care",
        breed: "Budgerigar",
        birthday: "2023-03-22",
        weight: 0.15,
        color_level: 1,
        sex: "M",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        animal_tag: AnimalTag.BIRD,
        name: "Phoenix",
        status: "Does Not Need Care",
        breed: "Lovebird",
        birthday: "2022-07-14",
        weight: 0.25,
        color_level: 2,
        sex: "F",
        created_at: new Date(),
        updated_at: new Date(),
      },
      // Bunnies
      {
        animal_tag: AnimalTag.BUNNY,
        name: "Snowball",
        status: "Needs Care",
        breed: "Holland Lop",
        birthday: "2022-04-25",
        weight: 3,
        color_level: 1,
        neutered: true,
        sex: "F",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        animal_tag: AnimalTag.BUNNY,
        name: "Cocoa",
        status: "Does Not Need Care",
        breed: "Netherland Dwarf",
        birthday: "2021-11-30",
        weight: 2.5,
        color_level: 2,
        neutered: true,
        sex: "M",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        animal_tag: AnimalTag.BUNNY,
        name: "Pepper",
        status: "Occupied",
        breed: "Mini Rex",
        birthday: "2023-01-08",
        weight: 4,
        color_level: 1,
        neutered: false,
        sex: "F",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        animal_tag: AnimalTag.BUNNY,
        name: "Oreo",
        status: "Needs Care",
        breed: "English Angora",
        birthday: "2022-08-17",
        weight: 5,
        color_level: 3,
        neutered: true,
        sex: "M",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        animal_tag: AnimalTag.BUNNY,
        name: "Honey",
        status: "Does Not Need Care",
        breed: "Flemish Giant",
        birthday: "2021-06-03",
        weight: 12,
        color_level: 2,
        neutered: true,
        sex: "F",
        created_at: new Date(),
        updated_at: new Date(),
      },
      // Small Animals
      {
        animal_tag: AnimalTag.SMALL_ANIMAL,
        name: "Peanut",
        status: "Needs Care",
        breed: "Guinea Pig",
        birthday: "2022-12-12",
        weight: 1.2,
        color_level: 1,
        sex: "M",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        animal_tag: AnimalTag.SMALL_ANIMAL,
        name: "Nibbles",
        status: "Does Not Need Care",
        breed: "Hamster",
        birthday: "2023-04-08",
        weight: 0.15,
        color_level: 1,
        sex: "F",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        animal_tag: AnimalTag.SMALL_ANIMAL,
        name: "Squeaky",
        status: "Occupied",
        breed: "Rat",
        birthday: "2022-10-20",
        weight: 0.5,
        color_level: 2,
        sex: "M",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        animal_tag: AnimalTag.SMALL_ANIMAL,
        name: "Patches",
        status: "Needs Care",
        breed: "Guinea Pig",
        birthday: "2023-02-14",
        weight: 1.1,
        color_level: 1,
        sex: "F",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        animal_tag: AnimalTag.SMALL_ANIMAL,
        name: "Gizmo",
        status: "Does Not Need Care",
        breed: "Chinchilla",
        birthday: "2021-09-25",
        weight: 0.8,
        color_level: 3,
        sex: "M",
        created_at: new Date(),
        updated_at: new Date(),
      },
    ]);

    // Seed Task Templates
    await queryInterface.bulkInsert("task_templates", [
      {
        task_name: "Morning Dog Walk",
        category: TaskCategory.WALK,
        instruction: "Take the dog for a 30-minute walk around the facility grounds. Check for any behavioral issues and note energy levels.",
      },
      {
        task_name: "Cage Cleaning",
        category: TaskCategory.HUSBANDRY,
        instruction: "Clean and disinfect the animal's living space. Replace bedding, clean food and water bowls, and check for any maintenance issues.",
      },
      {
        task_name: "Basic Training Session",
        category: TaskCategory.TRAINING,
        instruction: "Conduct a 15-minute basic obedience training session. Focus on sit, stay, and come commands. Use positive reinforcement techniques.",
      },
      {
        task_name: "Interactive Play Time",
        category: TaskCategory.GAMES,
        instruction: "Engage the animal in interactive play for 20 minutes. Use appropriate toys and monitor stress levels throughout the session.",
      },
      {
        task_name: "Socialization Activity",
        category: TaskCategory.PEN_TIME,
        instruction: "Allow supervised interaction with other compatible animals or volunteers. Monitor behavior and social cues for 30 minutes.",
      },
    ]);

    // Seed Tasks
    await queryInterface.bulkInsert("tasks", [
      {
        user_id: 7, // Amanda Garcia (volunteer)
        pet_id: 1, // Buddy (dog)
        task_template_id: 1, // Morning Dog Walk
        scheduled_start_time: new Date(Date.now() + 24 * 60 * 60 * 1000), // Tomorrow
        notes: "First walk for this volunteer with Buddy",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 5, // Lisa Davis (staff)
        pet_id: 6, // Whiskers (cat)
        task_template_id: 2, // Cage Cleaning
        scheduled_start_time: new Date(Date.now() + 2 * 60 * 60 * 1000), // In 2 hours
        start_time: new Date(),
        notes: "Weekly deep clean scheduled",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 3, // Dr. Emily Wilson (behaviourist)
        pet_id: 4, // Bella (dog)
        task_template_id: 3, // Basic Training Session
        scheduled_start_time: new Date(Date.now() + 4 * 60 * 60 * 1000), // In 4 hours
        notes: "Focus on recall training - dog shows promise",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        pet_id: 11, // Polly (bird)
        task_template_id: 4, // Interactive Play Time
        scheduled_start_time: new Date(Date.now() + 6 * 60 * 60 * 1000), // In 6 hours
        notes: "Unassigned task - needs volunteer with bird experience",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 8, // Kevin Martinez (volunteer)
        pet_id: 16, // Snowball (bunny)
        task_template_id: 5, // Socialization Activity
        scheduled_start_time: new Date(Date.now() + 8 * 60 * 60 * 1000), // In 8 hours
        notes: "Bunny needs socialization with other rabbits",
        created_at: new Date(),
        updated_at: new Date(),
      },
    ]);
  },

  down: async (queryInterface: QueryInterface) => {
    // Clean up tasks first
    await queryInterface.bulkDelete("tasks", {});
    
    // Clean up task templates
    await queryInterface.bulkDelete("task_templates", {});
    
    // Clean up pets
    await queryInterface.bulkDelete("pets", {});
    
    // Clean up users
    await queryInterface.bulkDelete("users", {
      auth_id: [
        "admin_001", "admin_002",
        "behaviourist_001", "behaviourist_002", 
        "staff_001", "staff_002",
        "volunteer_001", "volunteer_002"
      ],
    });
  },
};
