name: Lint codebase

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
      - "backend/typescript/**"
      - "backend/python/**"
  pull_request:
    branches:
      - main
    paths:
      - "frontend/**"
      - "backend/typescript/**"
      - "backend/python/**"

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Filter changed files
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            frontend:
              - "frontend/**"
            typescript-backend:
              - "backend/typescript/**"
            python-backend:
              - "backend/python/**"

      - name: Get Yarn cache directory
        id: yarn-cache-dir
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Cache Yarn dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: yarn-${{ runner.os }}-${{ hashFiles('frontend/yarn.lock', 'backend/typescript/yarn.lock') }}
          restore-keys: |
            yarn-${{ runner.os }}-

      - name: Set up Node.js
        if: steps.changes.outputs.frontend == 'true' || steps.changes.outputs.typescript-backend == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: "20.11.1"
          cache: "yarn"
          cache-dependency-path: |
            frontend/yarn.lock
            backend/typescript/yarn.lock

      - name: Install Node.js dependencies
        if: steps.changes.outputs.frontend == 'true' || steps.changes.outputs.typescript-backend == 'true'
        run: yarn --cwd ./frontend --prefer-offline && yarn --cwd ./backend/typescript --prefer-offline

      - name: Lint frontend
        if: steps.changes.outputs.frontend == 'true'
        working-directory: ./frontend
        run: yarn lint

      - name: Lint TypeScript backend
        if: steps.changes.outputs.typescript-backend == 'true'
        working-directory: ./backend/typescript
        run: yarn lint

      - name: Lint Python backend
        if: steps.changes.outputs.python-backend == 'true'
        working-directory: ./backend/python
        run: pip install black && python -m black --check .
